spring:
  application:
    name: session-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

server:
  port: 8081
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_URI:http://192.168.29.245:8761/eureka}"
  instance:
    hostname: 192.168.29.245
    prefer-ip-address: true

jwt:
  secret: "${JWT_SECRET:woidw0-9waj-9dawidnaiwndianidanipdnandianipdnapawdaopwndpawnd}"
